on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  console-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Check latest versions
        run: |
          deno run -A console/bumper.ts
          deno run --allow-read --allow-write --allow-net https://deno.land/x/dmm/mod.ts update
          cd tests
          deno run --allow-read --allow-write --allow-net https://deno.land/x/dmm/mod.ts update